### ISSUE TITLE
Test scenarios are groupped by "Without feature" name not a correct one

### ISSUE THREAD

**Issue by sgorbatenko** [allure-framework/allure-cucumberjs#2] opened 2016-05-17 11:21 UTC
I have feature file like:
@account
Feature: Account management

Scenario: Add account
    Given I am on the Accounts page1
    When I add new account1
    Then I should see account details1

  Scenario: Edit account
    Given I am on the Accounts page1
    When I edit new account1
    Then I should see account details1

Generated after I run protractor test and generate report I've got 
[allure-results.zip](https://github.com/allure-framework/cucumberjs-allure-reporter/files/268014/allure-results.zip)
![img-2016-05-17-14-16-06](https://cloud.githubusercontent.com/assets/10517127/15320574/f1dd6b14-1c39-11e6-83dd-6eab4be48258.png)

Why it is  named as " Without feature" and not as "Account management"
![img-2016-05-17-14-21-17](https://cloud.githubusercontent.com/assets/10517127/15320703/a75f2b26-1c3a-11e6-81b2-40d823105872.png)

**Comment by igniteram** [comment] 2016-05-31 13:06
@sgorbatenko 
you have set the @account tag before the feature that is why it is not identifying, try this : 

 Feature: Account management
@AddAccount
 Scenario: Add account
 Given I am on the Accounts page1
 When I add new account1
 Then I should see account details1

@EditAccount
Scenario: Edit account
Given I am on the Accounts page1
When I edit new account1
Then I should see account details1

It's always a good practice by giving tags at scenario level rather than feature level.

**Comment by piociek** [comment] 2016-05-31 13:11
@sgorbatenko Thanks! I'll check what's wrong.

**Comment by igniteram** [comment] 2016-06-01 13:33
@sgorbatenko @piociek up voting the above issue as i am also able to reproduce this issue, have to look at the root cause.
Note this issue happens in "Behaviour" section

**Comment by piociek** [comment] 2016-07-06 14:19
Works as intended. Please check this example: https://github.com/allure-framework/cucumberjs-allure-reporter/blob/master/features/label.feature

Closing.

**Closed as completed by piociek** 2016-07-06 14:19 UTC
